---
dependency:
  name: "galaxy"
  enabled: False

driver:
  name: "docker"

lint: |
  set -e
  yamllint .
  flake8

platforms:
  - name: "role-zsh-debian10"
    image: "python:3.7-buster"
    pre_build_image: true

provisioner:
  name: "ansible"
  log: true


verifier:
  name: "testinfra"


scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence # some action are not idempotent
    - side_effect
    - verify
    - cleanup
    - destroy
